### ISSUE TITLE
down下来编译通过 但是一运行就报错

### ISSUE THREAD

**Issue by qiandailu** [jrfeng/snow#1]
Unable to load class 'javafx.util.Pair'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

**Comment by jrfeng** [comment]
貌似不是本项目的原因，网上找了个解决方案：[`https://blog.csdn.net/henu_xiaohei/article/details/102496165`](https://blog.csdn.net/henu_xiaohei/article/details/102496165)

**Comment by jrfeng** [comment]
StackOverflow 有个类似的问题：[`https://stackoverflow.com/questions/52892627/can-not-resolve-import-javafx-util-pair-in-android-studio`](https://stackoverflow.com/questions/52892627/can-not-resolve-import-javafx-util-pair-in-android-studio)

**Comment by jrfeng** [comment]
找到问题了，有个依赖库使用了 `javafx.util.Pair` 类，但是从 Java11 开始 javafx 框架被移除了，因此如果你的 JDK 版本大于等于 Java11 就会有这个问题。

这个问题现在已经修复了，你可以再试一下。
