### ISSUE TITLE
PlayerViewModel Missing Meidaitems

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#10]
If i want get current playing media item details  i need user PlayerViewModel Right? But Using PlayerViewModel we cant get all music items. Missing "musicId", "album"  We need it for Add to favorite list ..

or There is any onother way to get Current playing Items? Or you can create function called something  like this 

    `currentmediaitem( Mediaitem mediaitem){
    }`

**Comment by jrfeng** [comment]
@webwayscript `PlayerClient#getPlayingMusicItem()`

**Comment by webwayscript** [comment]
Yes nice But it throwing some time null point how can i check if not null? PlayerClient is inside MainActivity.. I have another activity called PlayerActivity . i use MainActivity.playerClient.getPlayingMusicItem().getTitle()  inside oncreat PlayerActivity .. some time its null and crashed .. How can i check? this one i think not work

     `if(MainActivity.playerClient.getPlayingMusicItem().getTitle() != null){
            
        }`

**Comment by webwayscript** [comment]
I think Its only Update after Start playing music . I think I need PlayerClient#getNextPlayingMusicItem() and PlayerClient#getPriviesPlayingMusicItem() .. 

problem is when use skipToNext() or skipToPrevious() its Loading old played item only

**Comment by jrfeng** [comment]
@webwayscript I need the error stacktrace

**Comment by jrfeng** [comment]
if not connect or playlist is empty, `PlayerClient#getPlayingMusicItem()` will return null.

**Comment by webwayscript** [comment]
`MusicItem musicItem =  MainActivity.playerClient.getPlayingMusicItem();
        if(musicItem != null){
            Log.e(TAG, "onConnected: "+musicItem.getTitle() );
            title = musicItem.getTitle();
            iconUri = musicItem.getIconUri();
        }`

I used like above code  its working fine in another activity. But When use on item click Like this with  position its showing wrong item ( Showing previously played item)

    `MainActivity.playerClient.setPlaylist(createPlaylist(), selectedPos,true);`

**Comment by webwayscript** [comment]
Sorry I gave you So many question..In my listview with list of items, all items i just called "playerClient.setPlaylist(createPlaylist(), selectedPos,true);"  Its working Fine. My doubt .. I Must call "playPause(int position)" Like this ?

**Comment by jrfeng** [comment]
@webwayscript If you want play the clicked list item, you need call `playPause(int position)`, if the item is playing now, then will pause, otherwise will play this item.

**Comment by webwayscript** [comment]
when use playerClient.playPause(selectedPos); also gave wrong item if we use PlayerClient#getPlayingMusicItem().. if we click skipToNext and skipToPrevious its working fine ... I cant get first clicked Mediaitem on onother activity ..

**Comment by jrfeng** [comment]
@webwayscript Do you want to record playback history?

**Comment by jrfeng** [comment]
@webwayscript Maybe you need `PlayerClient#addOnPlayingMusicItemChangeListener(Player.OnPlayingMusicItemChangeListener)`

**Comment by webwayscript** [comment]
This kind of constructor connected with nothing  i used after oncreat this is right? 

    `public void addOnPlayingMusicItemChangeListener(Player.OnPlayingMusicItemChangeListener listener){

    }
erro:
Method 'addOnPlayingMusicItemChangeListener(snow.player.Player.OnPlayingMusicItemChangeListener)' is never used`

**Comment by jrfeng** [comment]
I dont known what you want to do, can you please describe it in detail?

**Comment by webwayscript** [comment]
ok First i un installed my app. Fresh install. When i call using "setPlaylist(createPlaylist(), selectedPos,true);" No media item showing when call "playerClient.getPlayingMusicItem();".   if we call skipToNext and skipToPrevious.. getPlayingMusicItem working fine

**Comment by jrfeng** [comment]
@webwayscript Your use of this library is wrong, maybe you should check your code, I can't help for this, sorry.
