### ISSUE TITLE
Notification Onclick

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#12]
how can i implement If notification onclick open activity? now its onclick nothing .. it must be open Mainactivity?

How can we add PlaybackStateCompat.ACTION_STOP ? or is missing?

**Comment by jrfeng** [comment]
sorry, i can't help for this. my computer is broken. I need buy a new one, before that, i can't provide any help.

**Comment by webwayscript** [comment]
I do t like this this is is correct??

    `public class MyMediaNotificationView extends PlayerService.MediaNotificationView {
    private static final String ACTION_SKIP_TO_PREVIOUS = "snow.player.action.SKIP_TO_PREVIOUS";
    private static final String ACTION_PLAY_PAUSE = "snow.player.action.PLAY_PAUSE";
    private static final String ACTION_SKIP_TO_NEXT = "snow.player.action.SKIP_TO_NEXT";
    
    @Override
    protected void onBuildNotification(androidx.core.app.NotificationCompat.Builder builder) {
        
        Intent intent = new Intent(getContext(), MainActivity.class);
        intent.putExtra("yourpackage.notifyId", PlayerService.NotificationView.CHANNEL_ID);
        PendingIntent pIntent = PendingIntent.getActivity(getContext(), 0, intent,
                PendingIntent.FLAG_UPDATE_CURRENT);

        androidx.media.app.NotificationCompat.MediaStyle mediaStyle =
                new androidx.media.app.NotificationCompat.MediaStyle()
                        .setMediaSession(getMediaSession().getSessionToken());
        mediaStyle.setShowActionsInCompactView(1, 2);
        
          builder.setSmallIcon(getSmallIconId())
                .setLargeIcon(getIcon())
                .setContentTitle(getContentTitle())
                .setContentText(getContentTitle())
                .setContentIntent(pIntent)
                .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
                .setPriority(NotificationCompat.PRIORITY_LOW)
                .setShowWhen(false)
                .setStyle(mediaStyle);

        addCustomAction(ACTION_SKIP_TO_PREVIOUS, new PlayerService.CustomAction() {
            @Override
            public void doAction(@NonNull Player player, @Nullable Bundle extras) {
                player.skipToPrevious();
            }
        });
        addCustomAction(ACTION_PLAY_PAUSE, new PlayerService.CustomAction() {
            @Override
            public void doAction(@NonNull Player player, @Nullable Bundle extras) {
                player.playPause();
            }
        });
        addCustomAction(ACTION_SKIP_TO_NEXT, new PlayerService.CustomAction() {
            @Override
            public void doAction(@NonNull Player player, @Nullable Bundle extras) {
                player.skipToNext();
            }
        });
        PendingIntent skipToPrevious = getCustomActionPendingIntent( ACTION_SKIP_TO_PREVIOUS );
        PendingIntent playPause = getCustomActionPendingIntent( ACTION_PLAY_PAUSE );
        PendingIntent skipToNext = getCustomActionPendingIntent( ACTION_SKIP_TO_NEXT );
        builder.addAction ( R.drawable.snow_ic_skip_previous, " skip_to_previous " , skipToPrevious);
        if (isPlayingState()) {
            builder.addAction(R.drawable.snow_ic_pause, "pause", playPause);
        } else {
            builder.addAction(R.drawable.snow_ic_play, "play", playPause);
        }

        builder.addAction(R.drawable.snow_ic_skip_next, "skip_to_next", skipToNext);
    }
    }`

I wonder about below code..  where i add PlayerService.NotificationView.CHANNEL_ID)???

NotificationCompat.Builder builder = new NotificationCompat.Builder(getContext(), PlayerService.NotificationView.CHANNEL_ID);

**Comment by jrfeng** [comment]
Example: set notification content intent

```java
public class MyMediaNotificationView extends PlayerService.MediaNotificationView {
    private PendingIntent pIntent;

    @Override
    protected void onInit() {
        Intent intent = new Intent(getContext(), MainActivity.class);
        pIntent = PendingIntent.getActivity(getContext(), 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
    }

    @Override
    protected void onBuildNotification(androidx.core.app.NotificationCompat.Builder builder) {
        super.onBuildNotification(builder);

        builder.setContentIntent(pIntent);
    } 
}
```

**Comment by webwayscript** [comment]
Thank you Its Working fine
