### ISSUE TITLE
Disable Show notification playerClient.connect

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#13]
1.When  playerClient.connect Notfication showing automatically . How can i disable this? .. Notification must show when  call play(),
2.And also that notification not possible remove .if we call  playerClient.shutdown(); or playerClient.disconnect(); its not remove 
(But its removed after playing song .  if call connect then disconnect() with out play notification not removes)

**Comment by jrfeng** [comment]
I will refactor notifation view, to make sure you can customize these behaviors.

**Comment by webwayscript** [comment]
Ok i will wait until you update..

**Comment by jrfeng** [comment]
refactor is complete, you can try it again.

**Comment by webwayscript** [comment]
Thank you Now its working fine . if we set SoundQuality Why music restarting? it is possible to fix it 
       `playerClient.setSoundQuality(SoundQuality.SUPER);`

**Comment by jrfeng** [comment]
Because when SoundQuality changed, player will switch audio source, so it will release old audio source and prepare new audio source.

**Comment by webwayscript** [comment]
Ok. but https://github.com/bullheadandplato/AndroidEqualizer this library working fine with playerClient.getAudioSessionId()

**Comment by jrfeng** [comment]
This library cannot meet the requirements. It will fail when the playing music item changed.

**Comment by webwayscript** [comment]
Ok thank you .. After fixing notification problem, now close button inside notification reopening app if we call exit(0); why?

     `final String CLOSE = "snow.player.action.ACTION_STOP";
        addCustomAction(CLOSE, new PlayerService.CustomAction() {
            @Override
            public void doAction(@NonNull Player player, @Nullable Bundle extras) {
                shutdown();
                exit(0);
            }
        });
`

**Comment by jrfeng** [comment]
This is the BUG of you App, there is nothing I can do about it.

**Comment by webwayscript** [comment]
> This library cannot meet the requirements. It will fail when the playing music item changed.

U need save equalizer setting then it work with all songs. check his demo. yes its not save setting with dialog but work with create new equalizer activity then need save setting onstop() then its work fine .  but some time it gave 

    `java.lang.UnsupportedOperationException: AudioEffect: invalid parameter operation ` with snow

https://github.com/segler-alex/RadioDroid he also changing soundquality with out restart song ( they using more sound quality ).

**Comment by jrfeng** [comment]
@webwayscript 

- Equalizer: Don't worry about that, this library will provide an EqualizerActivity.
- RadioDroid: I didn't find some useful information about sound quality in this App. If you know more about that, please let me known.

**Comment by webwayscript** [comment]
Thank you bro just now i found RadioDroid launching native equalizer that was my mistake

**Comment by webwayscript** [comment]
Dont forget to check new exoplayer release.. I think some thing new is there
