### ISSUE TITLE
I need play action request new mp3 get url

### ISSUE THREAD

**Issue by tolgatasci** [jrfeng/snow#15]
MusicItem song1 = new MusicItem.Builder()
                    .setTitle("test")
                    .setArtist("asd")
                    .setDuration(313520)
                    .setUri(url)
                    .setIconUri("http://p1.music.126.net/4tTN8CnR7wG4E1cauIPCvQ==/109951163240682406.jpg")
                    .build();
            BaseApp.playerClient.setPlaylist( new snow.player.playlist.Playlist.Builder()
                    .append(song1)
                    .build(), true);
My call application

	BaseApp.playerClient = PlayerClient.newInstance(this, MyPlayerService.class);

	@Override
    protected MusicPlayer onCreateMusicPlayer(@NonNull Context context, @NonNull MusicItem musicItem, @NonNull Uri uri) {

        String path = uri.getLastPathSegment();
       // I need new Request and call exoplayer My method SYNC not return
        Log.e("x",uri.toString());
        return new ExoMusicPlayer(context, mProgressiveMediaSourceFactory, uri);
    }

**Comment by jrfeng** [comment]
Can you describe it in detail?

**Comment by tolgatasci** [comment]
I don't want to enter in advance. Then I want to enter the url when it starts playing.
// I need new Request and call exoplayer My method SYNC not return
uri.toString() change new request call and return data new URL i want this
	@Override
	protected MusicPlayer onCreateMusicPlayer(@NonNull Context context, @NonNull MusicItem musicItem, @NonNull Uri uri) {

		String path = uri.getLastPathSegment();
	   // I need new Request and call exoplayer My method SYNC not return
		Log.e("x",uri.toString());
		return new ExoMusicPlayer(context, mProgressiveMediaSourceFactory, uri);
	}

**Comment by jrfeng** [comment]
You want to get the new URL from your server when play music, it's that so?

**Comment by tolgatasci** [comment]
yes changing url parametres

**Comment by jrfeng** [comment]
override method: `PlayerService#onRetrieveMusicItemUri(MusicItem, SoundQuality)`

**Comment by tolgatasci** [comment]
i know this method but  

    public Uri onRetrieveMusicItemUri(MusicItem item , SoundQuality q){
        
        AtomicReference<Uri> parse = new AtomicReference<>(Uri.parse(item.getUri()));
        newUrl(item.getUri(), (ResData<ResponseDoc>)
                response -> {

                   parse.set(Uri.parse(response.getUrl()));

                });
        Log.e("x",parse.get().toString());
        return parse.get();
    }

i dont async method

**Comment by jrfeng** [comment]
Just block this thread, it's fine.

**Comment by tolgatasci** [comment]
thank you
