### ISSUE TITLE
Cant create playlist

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#2]
Cannot resolve symbol 'MusicItemBuilder'
      
      ` MusicItem song1 = new MusicItemBuilder(313520, "http://music.163.com/song/media/outer/url?id=4875306")
                .setTitle("逍遥叹")
                .setArtist("胡歌")
                .setIconUri("http://p1.music.126.net/4tTN8CnR7wG4E1cauIPCvQ==/109951163240682406.jpg")
                .build();`

How i create playlist?

Also create clear demo

if we import your project there is error in demo debug

     `Unable to load class 'javafx.util.Pair'.
      Possible causes for this unexpected error include:
     Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
     Re-download dependencies and sync project (requires network)`

**Comment by jrfeng** [comment]
@webwayscript  This bug has been fixed:

`Unable to load class 'javafx.util.Pair'`

**Comment by jrfeng** [comment]
`MusicItemBuilder` is a new class, not release yet. If you want to use this class, you can change the version to `master-SNAPSHOT`, like this:

`implementation 'com.github.jrfeng.snow:player:master-SNAPSHOT'`

**Comment by webwayscript** [comment]
Thank you Bro  .. I will check now.. thank you for quick fix

**Comment by webwayscript** [comment]
Very Nice work .. We found some issue
1. Not work with latest Emulator ... Notification channel error
2. Exoplayer Not work with redirected url i think u need Okhttp (http://playerservices.streamtheworld.com/api/livestream-redirect/ARRBEAT_S01.aac)
3. Also m3u8 also not work {https://vidhttps.r.worldssl.net/thanthi-origin/liveabr/playlist.m3u8"}

4. I think idont know how can i add playlist using json api

ex:

     ` {
        "radio_id": "6665",
        "radio_title": "AR Rahman Radio",
        "radio_img": "http://hdfmradio.com/wp-content/uploads/2016/10/rahman-1-1.png",
        "radio_url": "http://playerservices.streamtheworld.com/api/livestream-redirect/ARRAHMANRADIO_S01.aac?lsid=idfa:155124521827-191&dist=tamilfmradio.tamilfmsongs",
        "cat_id": "24",
        "radio_type": "hd",
        "type": "radio"
    },
    {
        "radio_id": "6667",
        "radio_title": "AR Rahman Lite Radio",
        "radio_img": "http://hdfmradio.com/wp-content/uploads/2016/10/rahman-1-1.png",
        "radio_url": "http://playerservices.streamtheworld.com/api/livestream-redirect/ARRAHMANLITE_S01.aac?lsid=idfa:155124521827-191&dist=tamilfmradio.tamilfmsongs",
        "cat_id": "24",
        "radio_type": "hd",
        "type": "radio"
    },`

Thank you for this good Library ...

**Comment by jrfeng** [comment]
* Issue 2: You can read this: [`https://github.com/google/ExoPlayer/issues/1190#issuecomment-174997094`](https://github.com/google/ExoPlayer/issues/1190#issuecomment-174997094)
* Issue 3: The `exo` module only add the dependency of `exoplayer-core`, if you want play `m3u8` media, you need add dependency of `exoplayer-hls`, and use `HlsMediaSource.Factory` to create `ExoMusicPlayer` instance. You can read this: [`https://exoplayer.dev/hello-world.html`](https://exoplayer.dev/hello-world.html)

PS: I will finish wiki as soon as possible.

**Comment by webwayscript** [comment]
Api 29 Crash.. old api working fine

also missing Notification Icon...
   
    `		--------- beginning of crash
	2020-08-30 19:45:24.618 5082-5082/snow.player.debug E/AndroidRuntime: FATAL EXCEPTION: main
		Process: snow.player.debug, PID: 5082
		java.lang.IllegalArgumentException: Illegal null AudioFocusRequest
			at android.media.AudioManager.abandonAudioFocusRequest(AudioManager.java:2748)
			at media.helper.AudioFocusHelper.abandonAudioFocusAPI26(AudioFocusHelper.java:145)
			at media.helper.AudioFocusHelper.abandonAudioFocus(AudioFocusHelper.java:135)
			at snow.player.AbstractPlayer.notifyStopped(AbstractPlayer.java:817)
			at snow.player.AbstractPlayer.stop(AbstractPlayer.java:978)
			at snow.player.AbstractPlayer.onNewPlaylist(AbstractPlayer.java:1399)
			at snow.player.playlist.PlaylistEditor$OnNewPlaylistListener__ChannelHelper$Dispatcher.dispatch(PlaylistEditor$OnNewPlaylistListener__ChannelHelper.java:74)a`

**Comment by jrfeng** [comment]
@webwayscript These bugs have been fixed:

- [Not work with latest Emulator ... Notification channel error](https://github.com/jrfeng/snow/issues/2#issuecomment-683417003)
- [Api 29 Crash.. old api working fine](https://github.com/jrfeng/snow/issues/2#issuecomment-683426154)

**Comment by webwayscript** [comment]
Thank you Bro its Working Fine with latest api .. I need more fixes i will rise new thread ..
