### ISSUE TITLE
作者不更新了吗？

### ISSUE THREAD

**Issue by 2697a** [jrfeng/snow#21]
很棒的一个库，千万不要停止维护啊

**Comment by jrfeng** [comment]
更新啊，但最近有点忙，而且还没有想到要加什么新功能，如果你想到什么好的功能的话，欢迎提需求，如果能实现的话我会尽量加上去的。

**Comment by 2697a** [comment]
有点想法
1.边听边存
2.倍速播放
3.本地音乐模块
当然这些只是我的需求，还是要看作者的安排

**Comment by jrfeng** [comment]
因为这个库只是个音乐播放器框架，边听边存的话需要通过自定义播放器自行实现；倍速播放的话可以加上去；本地音乐播放我不是很清楚，你可以详细描述一下吗？

**Comment by 2697a** [comment]
> 因为这个库只是个音乐播放器框架，边听边存的话需要通过自定义播放器自行实现；倍速播放的话可以加上去；本地音乐播放我不是很清楚，你可以详细描述一下吗？

就是添加扫描本地音乐的功能

**Comment by jrfeng** [comment]
嗯嗯，明白，我会添加一个扫描本地音乐的工具的类的

**Comment by 2697a** [comment]
> 嗯嗯，明白，我会添加一个扫描本地音乐的工具的类的

嗯，多谢啦

**Comment by jrfeng** [comment]
@2697a 已添加对 “倍速播放” 的支持，扫描本地音乐的工具类我也会尽快添加的，感谢支持 ❤️❤️❤️

**Comment by jrfeng** [comment]
@2697a 因为框架默认的音乐播放器使用的是系统的 `MediaPlayer`, 因此最低需要 `API 23` 才支持倍速播放。不过 `ExoMusicPlayer` 支持更低 `Android` 版本上的倍速播放，如果你打算使用 `ExoMusicPlayer` 的话，请参考 `Wiki`：[使用 `ExoPlayer`](https://github.com/jrfeng/snow/wiki/%5BZH%5D-5.%E4%BD%BF%E7%94%A8-ExoPlayer)

**Comment by 2697a** [comment]
> @2697a 因为框架默认的音乐播放器使用的是系统的 `MediaPlayer`, 因此最低需要 `API 23` 才支持倍速播放。不过 `ExoPlayer` 支持更低 `Android` 版本上的倍速播放，如果你打算使用 `ExoPlayer` 的话，请参考 `Wiki`：[使用 `ExoPlayer`](https://github.com/jrfeng/snow/wiki/%5BZH%5D-5.%E4%BD%BF%E7%94%A8-ExoPlayer)

好的，刚看到，辛苦了

**Comment by jrfeng** [comment]
@2697a 已添加扫描本地音乐的工具类：`AudioScanner<T>`（[API 文档](https://jrfeng.github.io/snow-doc/snow/player/util/AudioScanner.html)）

> **提示**：已发布 `1.1` 版本，如需使用新增功能，可将依赖库升级至 `1.1` 版本。

**例：**

```java
AudioScanner audioScanner = new AudioScanner<>(this, new AudioScanner.AudioItemConverter());

audioScanner.scan(new AudioScanner.OnProgressUpdateListener<AudioScanner.AudioItem>() {
    @Override
    public void onStart() {
        // 该方法会在开始扫描前调用（在主线程调用）
    }

    @Override
    public void onProgressUpdate(int progress) {
        // 当扫描进度更新时会调用该方法（在主线程调用）
    }

    @Override
    public void onEnd(@NonNull List<AudioScanner.AudioItem> audioList, boolean cancelled) {
        // 该方法会在结束扫描或者扫描被取消后调用，并将扫描结果传递给该方法（在主线程调用）
    }
});
```

其他方法：

* `cancel()`：取消扫描
* `isScanning() `：当前是否正在扫描

更多内容，请参考 [API 文档](https://jrfeng.github.io/snow-doc/snow/player/util/AudioScanner.html)
