### ISSUE TITLE
在线音乐如果获取时长

### ISSUE THREAD

**Issue by cowoboy007** [jrfeng/snow#22]
我这边音乐不知道时长。需要播放获取后写入。有什么办法可以和这个库结合吗。我发现时长都是需要预先设置

**Comment by jrfeng** [comment]
目前时长都必须预先设置，不支持在播放时获取时长，不过我会把这个需求加上的。

**Comment by cowoboy007** [comment]
嗯嗯，尽快吧大佬。我现在是自己读到了。又重置了下，有点low

**Comment by jrfeng** [comment]
@cowoboy007 给 `PlayerService` 添加了一个新方法：

```java
protected void onPrepareMusicItem(
    MusicItem musicItem,
    SoundQuality soundQuality,
    AsyncResult<MusicItem> result
)
```

该方法会在歌曲即将播放前调用，你可以在该方法中对`MusicItem` 对象进行修改。例如，从服务器获取歌曲的播放时长、播放链接，并使用这些数据更新 `MusicItem` 对象。

对 `MusicItem` 对象的修改可能会被持久化保存到本地，请务必注意这一点。

该方法会在异步线程中执行，因此可以执行各种耗时操作，例如访问网络。

**注意**：如果你在 `onPrepareMusicItem` 方法中获取并修改了 `MusicItem` 的播放链接，但你同时又重写了 `PlayerService` 的 `onRetrieveMusicItemUri` 方法来获取歌曲的最新播放链接，则在播放歌曲时，会优先使用 `onRetrieveMusicItemUri` 方法获取到的播放链接。如果你仅仅只需要在播放时获取歌曲的最新播放链接，建议重写 `onRetrieveMusicItemUri` 方法即可。如果你在 `onPrepareMusicItem`  已经获取并修改了 `MusicItem` 的播放链接，则不需要再重写 `onRetrieveMusicItemUri` 方法。

**Comment by cowoboy007** [comment]
在线链接这个 我复写onRetrieveMusicItemUri这个解决了。主要是mediaplayer如何在prepared后。动态的把时长写入musicItem，同时还本地化

**Comment by jrfeng** [comment]
可以详细说下你需要 MediaPlayer 的时长的用处吗？

**Comment by cowoboy007** [comment]
服务器给不了我时长。我需要prepare后，把时长给到musicitem。

**Comment by jrfeng** [comment]
OK, 我看下有没有好的解决方案，如果有的话，我会加上的

**Comment by cowoboy007** [comment]
好的。感谢

**Comment by jrfeng** [comment]
@cowoboy007 你获取这个 duration 的主要用途是什么？可以详细描述一下使用场景吗？

**Comment by cowoboy007** [comment]
很简单哈。播放页面进度条需要时长对吧。服务器只给我url。我需要播放器内部把时长处理好，并且存储本地化，同时下次获取到了就不用再存储了

**Comment by cowoboy007** [comment]
就是播放器内部去把未设置时长的musicitem 管理起来。不需要创建播放列表的时候必须传

**Comment by jrfeng** [comment]
你的实时播放进度是使用 `PlayerViewModel` 还是 `LiveProgress` 实现的？

**Comment by cowoboy007** [comment]
PlayerViewModel

**Comment by cowoboy007** [comment]
和做个没关系吧。他只有进度。没有duration

**Comment by jrfeng** [comment]
`PlayerViewModel` 需要正确的 `duration ` 才能正常工作。

**Comment by jrfeng** [comment]
在不知道 `duration` 的情况下，你在创建 `MusicItem` 对象时把 `duration` 设置成了什么值？

**Comment by jrfeng** [comment]
@cowoboy007 为 `MusicItem.Builder` 添加了一个方法：`delayDuration()`。你可以在使用 `MusicItem.Builder` 构建 `MusicItem` 对象时调用该方法。这将延迟到播放器准备完毕后再获取 `MusicItem` 的 `duration`。调用该方法后，`PlayerViewModel` 的实时播放进度功能将能够正常工作。

例：

```java
MusicItem song = new MusicItem.Builder()
            .setTitle("title")
            .setArtist("artist")
            .delayDuration()        // 延迟获取歌曲的播放时长
            .setUri("url")
            .build();
```

PS: 因为是新添加的功能，可能会有 BUG，如果遇到了 BUG，欢迎反馈 😄😄😄

**Comment by jrfeng** [comment]
方法已重命名：`delayDuration()` -> `autoDuration()`

**Comment by cowoboy007** [comment]
嗯嗯，试了下。有个问题就是。这个duration 写入到mmkv了吗。感觉下次进来还是0.需要播放才能拿到。理论上第一次拿到后，应该存起来，以后都不需要再拿了。直接读取本地的

**Comment by jrfeng** [comment]
只会保存当前正在播放的歌曲的 duration

**Comment by cowoboy007** [comment]
大佬我这还有个需求就是定时器的选项多了一个播放当前音频后关闭。有什么思路能尽量少的改动接入吗

**Comment by jrfeng** [comment]
已重构睡眠定时器，增加方法：`setWaitPlayComplete(boolean)`

如果你需要睡眠定时器时间到时，等待当前正在播放的歌曲播放完成后再执行指定动作（例如，暂停播放），则可以调用 `PlayerClient#setWaitPlayComplete(boolean)` 方法并传入 `true`。

**Comment by cowoboy007** [comment]
大佬如果在后台运行，只保留服务了。我怎么监听进度，我在playservice里面监听progress貌似不起作用

**Comment by jrfeng** [comment]
是用来做 UI 展示吗？

**Comment by cowoboy007** [comment]
不是。当所有界面全部销毁了。我需要去监听付费音频，后台试听结束，需要pause 一下

**Comment by jrfeng** [comment]
在付费歌曲播放完成后暂停播放，不跳到下一曲？

**Comment by cowoboy007** [comment]
暂停就行，我看界面里面的进度都是做了个计时器。service应该是拿不到实施进度

**Comment by jrfeng** [comment]
是的，PlayerService 没有提供监听实时播放进度的 API。

**Comment by cowoboy007** [comment]
恩。我做个轮询，隔1s查询一次进度吧
