### ISSUE TITLE
Drag dismiss dialog?

### ISSUE THREAD

**Issue by omkar-tenkale** [jrfeng/snow#23]
Is it possible that any dialogs opened (input,message.. etc) can be dismissed with elastic drag down effect

after start dragging down, the dialog will translate down and when finger lifted , if enough translationY, dismiss dialog else restore to default position with animation

Can be see in bottomsheet beheviours and https://play.google.com/store/apps/details?id=bitpit.launcher

**Comment by jrfeng** [comment]
Sorry for the late reply. The `app` module is just a sample App, there are no plans to add more new features.

**Comment by omkar-tenkale** [comment]
no issues, Do you know any android library which facilitates such functionallity?

**Comment by jrfeng** [comment]
https://github.com/kongzue/DialogX

**Comment by omkar-tenkale** [comment]
ok thanks!
