### ISSUE TITLE
Android Latest Version Notification Problem 

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#25]
Android  Notification problem

android 30

1. Notification icon not showing
2. Player Notification not possible remove .. after stopped and exit app media notification still showing.

android 32
1. Notification icon not showing

**Comment by jrfeng** [comment]
@webwayscript OK, I'll check it.

**Comment by jrfeng** [comment]
@webwayscript Can you a URL of a icon that cannot be loaded?

**Comment by jrfeng** [comment]
@webwayscript  I didn't find the problem you reported. Can you provide more information?

**Comment by webwayscript** [comment]
Thanku its fixed in new update
