### ISSUE TITLE
getPlayProgress 使用问题

### ISSUE THREAD

**Issue by copperdong** [jrfeng/snow#26]
您好，我想用一个定时器去读取当前进度，但是播放时读取的时间都是一样，点击暂停后才更新

```
       Handler handler= new Handler();
        Runnable runnable= new Runnable(){
            @Override
            public void run() {
                int time =  mPlayerClient.getPlayProgress();
                Log.d("runnable", "time" + time);
                handler.postDelayed(this, 1000);
            }
        };
        handler.postDelayed(runnable, 1000);
```

**Comment by jrfeng** [comment]
可以使用 LiveProgress 监听实时播放进度。

具体使用方法，请查看：[`https://github.com/jrfeng/snow/issues/19#issuecomment-793897071`](https://github.com/jrfeng/snow/issues/19#issuecomment-793897071)

**Comment by copperdong** [comment]
> 可以使用 LiveProgress 监听实时播放进度。
> 
> 具体使用方法，请查看：[`https://github.com/jrfeng/snow/issues/19#issuecomment-793897071`](https://github.com/jrfeng/snow/issues/19#issuecomment-793897071)

OK，谢谢
