### ISSUE TITLE
Custom Notification icon

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#28]
It is possible change Notification icons? i want use my won icons for play and pause and next privies icons.
Can you add this function?

**Comment by jrfeng** [comment]
See wiki: [`https://github.com/jrfeng/snow/wiki/%5BEN%5D-4.Custom-Notification`](https://github.com/jrfeng/snow/wiki/%5BEN%5D-4.Custom-Notification)

**Comment by webwayscript** [comment]
we read you wiki .. thank you for this
1. Why there is three different kind Notification function? its confusing..
   1.extends PlayerService.MediaNotificationView
  2. extends PlayerService.NotificationView
  3. extends NotificationView 
 we need add all in PlayerService ? then how?

this is my MyCustomNotificationView

      public class MyCustomNotificationView extends PlayerService.MediaNotificationView {
    private PendingIntent pIntent;
    private static final String ACTION_STOP = "STOP";
    private PendingIntent mStop;

    private static final String ACTION_SKIP_TO_PREVIOUS = "SKIP_TO_PREVIOUS";
    private PendingIntent mSkipToPrevious;

    @Override
    protected void onInit(Context context) {
        super.onInit(context);
        Intent intent = new Intent(getContext(), MainActivity.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S) {
            pIntent = PendingIntent.getActivity(getContext(), 0, intent, PendingIntent.FLAG_MUTABLE);
        } else {
            pIntent = PendingIntent.getActivity(getContext(), 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
        }

        mStop = buildCustomAction(ACTION_STOP, new PlayerService.CustomAction() {
            @Override
            public void doAction(@NonNull Player player, @Nullable Bundle extras) {
                shutdown();
                if(MainActivity.fa != null){
                    MainActivity.fa.finishAffinity();
                }
                System.exit(0);
            }
        });

        mSkipToPrevious = buildCustomAction(ACTION_SKIP_TO_PREVIOUS, new PlayerService.CustomAction() {
            @Override
            public void doAction(@NonNull Player player, @Nullable Bundle extras) {
                player.skipToPrevious();
            }
        });
    }

    @Override
    protected void onBuildMediaStyle(NotificationCompat.MediaStyle mediaStyle) {
        super.onBuildMediaStyle(mediaStyle);
        mediaStyle.setShowActionsInCompactView(1, 3);
    }

    @Override
    protected void onBuildNotification(androidx.core.app.NotificationCompat.Builder builder) {
        super.onBuildNotification(builder);
        builder.setContentIntent(pIntent);
        builder.addAction(R.drawable.ic_action_close, "close", mStop);
        builder.addAction(R.drawable.ic_action_mute, "skip_to_previous", mSkipToPrevious);
    }
}

all are working fine but "mSkipToPrevious" icon added extra not replacing old one . now i have 5 controls in notification

**Comment by jrfeng** [comment]
If you just want to customize the notification button icons, extends `PlayerService.MediaNotificationView`.

If you don't need the default buttons, please don't call  `super.onBuildNotification(builder)` on `onBuildNotification()` method.

If you just want to replace the default button icon, also do not call  `super.onBuildNotification(builder)` on `onBuildNotification()` method,  and add the following code to the method and replace the icon with your own icon:

```java
builder.addAction(R.mipmap.snow_ic_notif_skip_to_previous/*replace icon*/, "skip_to_previous", doSkipToPrevious());

if (isPlayingState()) {
    builder.addAction(R.mipmap.snow_ic_notif_pause/*replace icon*/, "pause", doPlayPause());
} else {
    builder.addAction(R.mipmap.snow_ic_notif_play/*replace icon*/, "play", doPlayPause());
}

builder.addAction(R.mipmap.snow_ic_notif_skip_to_next/*replace icon*/, "skip_to_next", doSkipToNext());
```

**Comment by webwayscript** [comment]
ok thank for your reply. 
if we remove "super.onBuildNotification(builder) ".. notification not showing 
if we add "builder.addAction(R.drawable.ic_skip_previous, "skip_to_previous", doSkipToPrevious());" i have one new icon in notification .

**Comment by jrfeng** [comment]
```java
@Override
protected void onBuildNotification(androidx.core.app.NotificationCompat.Builder builder) {
    // delete
    // super.onBuildNotification(builder);


    // add the following code to the method and replace the icon with your own icon
    builder.addAction(R.mipmap.snow_ic_notif_skip_to_previous/*replace icon*/, "skip_to_previous", doSkipToPrevious());

    if (isPlayingState()) {
        builder.addAction(R.mipmap.snow_ic_notif_pause/*replace icon*/, "pause", doPlayPause());
    } else {
        builder.addAction(R.mipmap.snow_ic_notif_play/*replace icon*/, "play", doPlayPause());
    }

    builder.addAction(R.mipmap.snow_ic_notif_skip_to_next/*replace icon*/, "skip_to_next", doSkipToNext());
    // *******************************

    builder.setContentIntent(pIntent);
    builder.addAction(R.drawable.ic_action_close, "close", mStop);
    builder.addAction(R.drawable.ic_action_mute, "skip_to_previous", mSkipToPrevious);
}
```

**Comment by webwayscript** [comment]
yes its working now thank you
