### ISSUE TITLE
How can I add images of songs in local music and album ?

### ISSUE THREAD

**Issue by salman660** [jrfeng/snow#35]
I was just wondering how could I add images for the Albums and Local music to make the user experience even better.

**Comment by jrfeng** [comment]
Do you mean embedded picture?

**Comment by salman660** [comment]
yes like these over here:
![Screenshot_2022_0729_211252.jpg](https://user-images.githubusercontent.com/56877461/181801038-fc669b3f-8147-4432-950d-7370ece3b725.jpg)

**Comment by jrfeng** [comment]
Jaudiotagger can  do that. see [`http://www.jthink.net/jaudiotagger/`](http://www.jthink.net/jaudiotagger/)

**Comment by salman660** [comment]
thanks :)

**Comment by jrfeng** [comment]
If you only want to read the metadata of audio files, android [`MediaMetaDataRetriever`](https://developer.android.com/reference/android/media/MediaMetadataRetriever) may be a better choice.
