### ISSUE TITLE
moveMusicItem 移动歌曲位置有问题啊。

### ISSUE THREAD

**Issue by Janzjoy** [jrfeng/snow#37]
复现方法：将一首处于当前播放歌曲下方的item移动到当前播放歌曲的上方，再把一首处于当前播放歌曲上方的item移动到当前播放歌曲的下方，然后点击下一首，播放的还是当前播放的歌曲。

**Comment by jrfeng** [comment]
已经修复了

**Comment by Janzjoy** [comment]
> 已经修复了

什么时候更新啊？可以加一个“音量均衡”功能吗？可以修改一下随机播放算法吗，就是把原有的播放列表打乱成一个新的播放列表来进行随机播放。

**Comment by jrfeng** [comment]
这个 issue 先关闭了，新需求的话建个新的 issue 讨论吧 :smile:
