### ISSUE TITLE
“"音量均衡”功能和修改”随机播放“算法

### ISSUE THREAD

**Issue by Janzjoy** [jrfeng/snow#38]
可以加一个"音量均衡"功能吗？可以修改一下随机播放算法吗，就是把原有的播放列表打乱成一个新的播放列表来进行随机播放。

**Comment by jrfeng** [comment]
“音量均衡”是指什么，不是很明白 :joy:

**Comment by Janzjoy** [comment]
> "音量均衡"是指什么，不是很明白😂

就是歌曲之间的音量保持统一

**Comment by jrfeng** [comment]
抱歉，真没听过“音量均衡”这个概念，你是指“均衡器”吗？像下面图片中的这种：
![](https://github.com/jrfeng/snow/raw/master/picture/screenshot-equalizer_zh.png)

**Comment by Janzjoy** [comment]
> 抱歉，真没听过“音量均衡”这个概念，你是指“均衡器”吗？像下面图片中的这种： ![](https://github.com/jrfeng/snow/raw/master/picture/screenshot-equalizer_zh.png)

不是的，没听过就算了，这个东西遇人不是很有用。那随机算法能改吗😶

**Comment by jrfeng** [comment]
可在增加一个支持自定义随机算法的功能。可以详细说下具体需求吗？

**Comment by Janzjoy** [comment]
> 可在增加一个支持自定义随机算法的功能。可以详细说下具体需求吗？

就是把播放列表顺序随机打乱，然后按照打乱后的列表进行顺序播放和获取，切换回“顺序”和“循环”播放模式就把列表换回原来的就行了🫥

**Comment by jrfeng** [comment]
:ok_hand: 了解了，有空的话我会加上的

**Comment by Janzjoy** [comment]
> 👌 了解了，有空的话我会加上的

好的，谢谢

**Comment by jrfeng** [comment]
抱歉，将播放列表随机打乱这个功能可能无法实现，因为将播放列表随机打乱会与编辑播放列表功能冲突。例如，将播放模式设为了“随机播放”并且将播放列表随机打乱，如果后续往播放列表中添加了新的歌曲，新的歌曲在播放列表中的位置是无法确定的；或者要移动歌曲在播放列表中的位置，新的位置也是无法确定的。

**Comment by Janzjoy** [comment]
> 抱歉，将播放列表随机打乱这个功能可能无法实现，因为将播放列表随机打乱会与编辑播放列表功能冲突。例如，将播放模式设为了“随机播放”并且将播放列表随机打乱，如果后续往播放列表中添加了新的歌曲，新的歌曲在播放列表中的位置是无法确定的；或者要移动歌曲在播放列表中的位置，新的位置也是无法确定的。

好的，确实存在很多问题
