### ISSUE TITLE
AppWidget 怎么接收不到广播啊？

### ISSUE THREAD

**Issue by Janzjoy** [jrfeng/snow#39]
有示例代码吗？
我按照文档来写的，接收不到广播啊。🙃

**Comment by Janzjoy** [comment]
下载源码，把“snow.player.appwidget.action.PLAYER_STATE_CHANGED”改成“android.appwidget.action.APPWIDGET_UPDATE”，注释“intent.addCategory(playerService.getName())”才正常。😶

**Comment by jrfeng** [comment]
BUG 已修改，具体使用方法请查看 Wiki：[`https://github.com/jrfeng/snow/wiki/%5BZH%5D-2.%E8%BF%9B%E9%98%B6#appwidget`](https://github.com/jrfeng/snow/wiki/%5BZH%5D-2.%E8%BF%9B%E9%98%B6#appwidget)

**Comment by Janzjoy** [comment]
> 

还是不行啊，我安卓13测试机无法接收到广播更新啊

**Comment by jrfeng** [comment]
在 Android 13 模拟器上测试可以接收到广播。可以在你的测试机上运行 debug 模块，把测试用的 AppWidget 添加到桌面，看能不能接收到广播。

**Comment by Janzjoy** [comment]
> 在 Android 13 模拟器上测试可以接收到广播。可以在你的测试机上运行 debug 模块，把测试用的 AppWidget 添加到桌面，看能不能接收到广播。

我已经把appwidget添加到桌面了，还是无法正常接收啊😕

**Comment by jrfeng** [comment]
试下在代码中调用 `Context.registerReceiver()` 注册下广播接收器。

**Comment by Janzjoy** [comment]
> 试下在代码中调用 `Context.registerReceiver()` 注册下广播接收器。
怎么弄啊，我不会啊😅

**Comment by jrfeng** [comment]
把你的 `AppWidgteProvider` 当广播接收器注册就行。

**Comment by jrfeng** [comment]
不需要试了，这个方法没用 :joy:

**Comment by jrfeng** [comment]
你的测试机型号是什么？可以截个图看下吗？

**Comment by Janzjoy** [comment]
> 你的测试机型号是什么？可以截个图看下吗？

好的，reaime getneo3
![QQ图片20230216131937](https://user-images.githubusercontent.com/108626070/219275537-bcd364ac-9d2a-4b19-a1ac-d705a45bc1cd.jpg)

**Comment by jrfeng** [comment]
增加了一种新的刷新 `AppWidget` 的方法，具体请查看 Wiki：[`https://github.com/jrfeng/snow/wiki/%5BZH%5D-2.%E8%BF%9B%E9%98%B6#appwidget`](https://github.com/jrfeng/snow/wiki/%5BZH%5D-2.%E8%BF%9B%E9%98%B6#appwidget)

**Comment by Janzjoy** [comment]
> 增加了一种新的刷新 `AppWidget` 的方法，具体请查看 Wiki：[`https://github.com/jrfeng/snow/wiki/%5BZH%5D-2.%E8%BF%9B%E9%98%B6#appwidget`](https://github.com/jrfeng/snow/wiki/%5BZH%5D-2.%E8%BF%9B%E9%98%B6#appwidget)

谢谢，它正常工作
