### ISSUE TITLE
Some url with some Api version Not work

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#4]
Old Api version 18
1.M3u8 Not work
2. Redirected Url working fine

New Api version 29
1.M3u8 working fine
2. Redirect url not work

Both working fine with exoplayer demo app

http://playerservices.streamtheworld.com/api/livestream-redirect/ARRBEAT_S01.aac     ( Redirected play)
https://vidhttps.r.worldssl.net/thanthi-origin/liveabr/playlist.m3u8

We added 
' android:usesCleartextTraffic="true"
   android:networkSecurityConfig="@xml/network_security_config"

**Comment by jrfeng** [comment]
ExoPlayer doesn't follow cross-protocol redirects by default

**Comment by webwayscript** [comment]
ok you can add it in your SNAPSHOT? we are waiting for further testing

**Comment by jrfeng** [comment]
This repository has added `jitpack` support, you can built it yourself: [`https://jitpack.io/#jrfeng/snow`](https://jitpack.io/#jrfeng/snow)

**Comment by webwayscript** [comment]
i Dont know why ..


implementation 'com.github.jrfeng.snow:player:master-651f631386-1'

    `Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve 
    com.github.jrfeng.snow:player:master-651f631386-1.`

**Comment by webwayscript** [comment]
https://github.com/jitpack/jitpack.io/issues/3758

**Comment by jrfeng** [comment]
Have you tried this: [`https://github.com/jitpack/jitpack.io/issues/3758#issuecomment-630306373`](https://github.com/jitpack/jitpack.io/issues/3758#issuecomment-630306373)

**Comment by webwayscript** [comment]
Yes  its not work

maven { url 'https://www.jitpack.io' }
and 
implementation 'com.github.jrfeng.snow:player:master-651f631386-1'

error:

     `Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve 
     com.github.jrfeng.snow:player:master-651f631386-1.`

Pls check 

"make the library readable to everyone."

**Comment by jrfeng** [comment]
OK, I'll publish a new release, you can try it again.

**Comment by webwayscript** [comment]
using implementation 'com.github.jrfeng.snow:player:1.0-alpha5' 
after invalided /cache /restarted

Same issue Old Api version 18 
ur: https://vidhttps.r.worldssl.net/thanthi-origin/liveabr/playlist.m3u8

     `09-01 11:23:28.494 2306-2306/com.example.snowtest E/TAG: onConnected: true
     09-01 11:23:42.025 2306-2318/com.example.snowtest E/MediaPlayer: error (1, -1004)
     09-01 11:23:42.025 2306-2306/com.example.snowtest E/MediaPlayer: Error (1,-1004)
     09-01 11:23:42.025 2306-2306/com.example.snowtest E/MediaMusicPlayer: MediaPlayer Error[what: 1, extra: -1004]
   09-01 11:23:42.025 2306-2306/com.example.snowtest E/MusicPlayer: errorCode:5`

**Same url working fine with api 29 emulator**

Same issue Old Api version 20
url : http://playerservices.streamtheworld.com/api/livestream-redirect/HARRISJAYARAJ_S01.aac 
Not no sound nio error (Not work)
**Working fine Api version 18 emulator**

Also no notification icon api level 18..
notification icon showing working fine api level29

**Comment by jrfeng** [comment]
@webwayscript OK, I'll check it out.

**Comment by jrfeng** [comment]
This doesn't seem to be a bug in this project.

Maybe you can check this StackOverflow post: [https://stackoverflow.com/a/51285550/4768512](https://stackoverflow.com/a/51285550/4768512)

**Comment by webwayscript** [comment]
yes .. this is the problem.. I think we need fix inside our app or your project library?
ok i will check it inside my app

**Comment by webwayscript** [comment]
No its not work .. also not work all m3u8 in old apimlevel 18
another url : http://airlsmp6-lh.akamaihd.net/i/AIRLSMP134_1@369210/master.m3u8

also i try with 

oncreat ;

      `try {
        ProviderInstaller.installIfNeeded(getApplicationContext());
        SSLContext sslContext;
        sslContext = SSLContext.getInstance("TLSv1.2");
        sslContext.init(null, null, null);
        sslContext.createSSLEngine();
    } catch (GooglePlayServicesRepairableException | GooglePlayServicesNotAvailableException
            | NoSuchAlgorithmException | KeyManagementException e) {
        e.printStackTrace();
    }`

implementation 'com.google.android.gms:play-services-auth:18.1.0'

not work m3u8 in old api level

**Comment by webwayscript** [comment]
I received following error when i use your GitHub project 
Ex url": http://airlsmp6-lh.akamaihd.net/i/AIRLSMP134_1@369210/master.m3u8

    `snow.player.debug E/ExoMusicPlayer: com.google.android.exoplayer2.ExoPlaybackException: 
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors 
    (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, 
    FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.`

**Comment by jrfeng** [comment]
Maybe you should check your audio source. This is not a bug in this project, I can't fix it, sorry.

**Comment by webwayscript** [comment]
https://github.com/jrfeng/snow/blob/master/exo/src/main/java/snow/player/exo/ExoMusicPlayer.java
there is no HlsMediaSourceFactory ...

**Comment by webwayscript** [comment]
http://airlsmp6-lh.akamaihd.net/i/AIRLSMP134_1@369210/master.m3u8
this source very popular and no 1 audio video source from akamaihd.net...

**Comment by jrfeng** [comment]
> https://github.com/jrfeng/snow/blob/master/exo/src/main/java/snow/player/exo/ExoMusicPlayer.java
> there is no HlsMediaSourceFactory ...

Maybe you should learn how to use `ExoPlayer`? Don't mind, I'll create a helper to simplify the process.

**Comment by webwayscript** [comment]
i use like this all urls working fine. 

    `private OkHttpDataSourceFactory dataSourceFactory;
    private SimpleExoPlayer exoPlayer;

	onCreate
	okHttpClient = new OkHttpClient.Builder()
					.connectTimeout(10, TimeUnit.SECONDS)
					.writeTimeout(10, TimeUnit.SECONDS)
					.readTimeout(10, TimeUnit.SECONDS)
					.build();
	exoPlayer = new SimpleExoPlayer.Builder(context).build();
	dataSourceFactory = new OkHttpDataSourceFactory(okHttpClient, Util.getUserAgent(context, useragent));

	 private void prepareToPlay(Uri uri) {
		if( String.valueOf(uri).contains("m3u8") ) {
			MediaSource videoSource = new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(uri);
			exoPlayer.prepare(videoSource);
		}else{
			MediaSource videoSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(uri);
			exoPlayer.prepare(videoSource);
		}
	}`

This code all m3u8 with or with https working fine  .. and also all redirected working fine.. its working fine from api level 16 up to latest version.. I dont know why its not working with your library 

Just now i found you using more code in MyFactory.java.. May be okhttp fix all https problem ..

**Comment by jrfeng** [comment]
@webwayscript  Thanks for feedback, I'll check it carefully.

**Comment by jrfeng** [comment]
@webwayscript Can you provide some url of `m3u8` media? If it's private, you can send it to my email: `jrfeng331@qq.com`
