### ISSUE TITLE
MIUI14上通知栏专辑封面显示问题

### ISSUE THREAD

**Issue by Janzjoy** [jrfeng/snow#40]
MIUI14通知栏专辑封面显示的是上一首的。🙃

**Comment by jrfeng** [comment]
没这个问题吧？找了台小米手机测试下，可以更新

**Comment by jrfeng** [comment]
小米音乐控制器确实无法正常显示封面，我找下有没有什么办法可以修复。

**Comment by Janzjoy** [comment]
> 小米音乐控制器确实无法正常显示封面，我找下有没有什么办法可以修复。

好的，谢谢

**Comment by jrfeng** [comment]
BUG 已修复

**Comment by Janzjoy** [comment]
> 错误已修复

什么时候更新发包啊😁
