### ISSUE TITLE
没有设置播放音量大小的方法吗

### ISSUE THREAD

**Issue by Janzjoy** [jrfeng/snow#46]

**Comment by Janzjoy** [comment]
> 没加这功能，要调节音量大小的话，设置系统音量就行了。

需要只调节歌曲播放音量，设置系统音量会影响用户使用体验啊

**Comment by jrfeng** [comment]
:ok_hand: OK，我会加上这个功能的

**Comment by Janzjoy** [comment]
> 👌 OK，我会加上这个功能的

好的，谢谢

**Comment by jrfeng** [comment]
功能已添加。

对应的方法：

- `PlayerClient#setVolume(float volume)`
- `PlayerClient#getVolume()`
- `PlayerClient#addOnVolumeChangeListener()`
- `PlayerClient#removeOnVolumeChangeListener()`
- `PlayerViewModel#getVolume()`
- `PlayerViewModel#setVolume()`

**Comment by Janzjoy** [comment]
> 功能已添加。
> 
> 对应的方法：
> 
> * `PlayerClient#setVolume(float volume)`
> * `PlayerClient#getVolume()`
> * `PlayerClient#addOnVolumeChangeListener()`
> * `PlayerClient#removeOnVolumeChangeListener()`
> * `PlayerViewModel#getVolume()`
> * `PlayerViewModel#setVolume()`

好的
