### ISSUE TITLE
1.2.11 多次点击播放暂停会出现无声音播放

### ISSUE THREAD

**Issue by Janzjoy** [jrfeng/snow#47]
切歌才恢复音量。

还有播放模式设置PlayMode.SINGLE_ONCE，每次点击上一曲播放都会回到第一首歌曲播放

**Comment by jrfeng** [comment]
BUG 已修复

**Comment by Janzjoy** [comment]
> BUG 已修复

播放模式问题修复了吗？我下载最新源码还是有问题

**Comment by Janzjoy** [comment]
> BUG 已修复

不好意思，问题修复了，谢谢
