### ISSUE TITLE
[Feature Request] Need Mute audio on call

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#5]
Need Mute audio on Call received. Also need enable disable function

1. On call receive Need Mute audio
2. auto play after call finished  .. need enable disable function 

1.Mute all other incoming sound need enable disable function ( Whats App call message and if open other audio app)
2.auto play after mute finished  .. need true/ false function

**Comment by jrfeng** [comment]
I don’t know very well, can you please describe it in detail?
