### ISSUE TITLE
Media Notification Not closed 

### ISSUE THREAD

**Issue by Naguchennai** [jrfeng/snow#52]
android api 33 .. after closed app Media Notification Not closed  
even we called all 

    
    @Override
    protected void onDestroy() {
        super.onDestroy();
        if(mPlayerClient !=null){
            mPlayerClient.stop();
            mPlayerClient.disconnect();
            mPlayerClient.shutdown();
        }
    }

Still notification showing ... need to be closed manuly...pls check

**Comment by jrfeng** [comment]
Do not call `mPlayerClient.disconnect()`.

**Comment by Naguchennai** [comment]
Yes thank you its working fine now
