### ISSUE TITLE
设置音量暂停恢复播放后音量设定值会失效啊

### ISSUE THREAD

**Issue by Janzjoy** [jrfeng/snow#57]

**Comment by jrfeng** [comment]
复现步骤是什么？

**Comment by Janzjoy** [comment]
先播放音乐，设置音量（0.2F），点击暂停，然后点击继续播放音乐，这个时候声音就会变大，再设置1.0F的音量会发现没有变化

**Comment by Janzjoy** [comment]
> 复现步骤是什么？
先播放音乐，设置音量（0.2F），点击暂停，然后点击继续播放音乐，这个时候声音就会变大，再设置1.0F的音量会发现没有变化
