### ISSUE TITLE
引入之后，MMKV版本冲突，如何解决

### ISSUE THREAD

**Issue by hidemobile** [jrfeng/snow#58]
implementation 'com.tencent:mmkv:1.3.2'，编译提示冲突，应该怎么解决，谢谢
Duplicate class com.tencent.mmkv.BuildConfig found in modules jetified-mmkv-1.3.2-runtime (com.tencent:mmkv:1.3.2) and jetified-mmkv-static-1.2.12-runtime (com.tencent:mmkv-static:1.2.12)
Duplicate class com.tencent.mmkv.MMKV found in modules jetified-mmkv-1.3.2-runtime (com.tencent:mmkv:1.3.2) and jetified-mmkv-static-1.2.12-runtime (com.tencent:mmkv-static:1.2.12)
Duplicate class com.tencent.mmkv.MMKV1foundinmodulesjetified−mmkv−1.3.2−runtime(com.tencent:mmkv:1.3.2)andjetified−mmkv−static−1.2.12−runtime(com.tencent:mmkv−static:1.2.12)Duplicateclasscom.tencent.mmkv.MMKV
LibLoader found in modules jetified-mmkv-1.3.2-runtime (com.tencent:mmkv:1.3.2) and jetified-mmkv-static-1.2.12-runtime (com.tencent:mmkv-static:1.2.12)
Duplicate class com.tencent.mmkv.MMKVContentChangeNotification found in modules jetified-mmkv-1.3.2-runtime (com.tencent:mmkv:1.3.2) and jetified-mmkv-static-1.2.12-runtime (com.tencent:mmkv-static:1.2.12)
Duplicate class com.tencent.mmkv.MMKVContentProvider found in modules jetified-mmkv-1.3.2-runtime (com.tencent:mmkv:1.3.2) and jetified-mmkv-static-1.2.12-runtime (com.tencent:mmkv-static:1.2.12)
Duplicate class com.tencent.mmkv.MMKVHandler found in modules jetified-mmkv-1.3.2-runtime (com.tencent:mmkv:1.3.2) and jetified-mmkv-static-1.2.12-runtime (com.tencent:mmkv-static:1.2.12)
Duplicate class com.tencent.mmkv.MMKVLogLevel found in modules jetified-mmkv-1.3.2-runtime (com.tencent:mmkv:1.3.2) and jetified-mmkv-static-1.2.12-runtime (com.tencent:mmkv-static:1.2.12)
Duplicate class com.tencent.mmkv.MMKVRecoverStrategic found in modules jetified-mmkv-1.3.2-runtime (com.tencent:mmkv:1.3.2) and jetified-mmkv-static-1.2.12-runtime (com.tencent:mmkv-static:1.2.12)
Duplicate class com.tencent.mmkv.NativeBuffer found in modules jetified-mmkv-1.3.2-runtime (com.tencent:mmkv:1.3.2) and jetified-mmkv-static-1.2.12-runtime (com.tencent:mmkv-static:1.2.12)
Duplicate class com.tencent.mmkv.ParcelableMMKV found in modules jetified-mmkv-1.3.2-runtime (com.tencent:mmkv:1.3.2) and jetified-mmkv-static-1.2.12-runtime (com.tencent:mmkv-static:1.2.12)
Duplicate class com.tencent.mmkv.ParcelableMMKV1foundinmodulesjetified−mmkv−1.3.2−runtime(com.tencent:mmkv:1.3.2)andjetified−mmkv−static−1.2.12−runtime(com.tencent:mmkv−static:1.2.12)Duplicateclasskotlin.collections.jdk8.CollectionsJDK8Ktfoundinmodulesjetified−kotlin−stdlib−1.8.0(org.jetbrains.kotlin:kotlin−stdlib:1.8.0)andjetified−kotlin−stdlib−jdk8−1.6.21(org.jetbrains.kotlin:kotlin−stdlib−jdk8:1.6.21)Duplicateclasskotlin.internal.jdk7.JDK7PlatformImplementationsfoundinmodulesjetified−kotlin−stdlib−1.8.0(org.jetbrains.kotlin:kotlin−stdlib:1.8.0)andjetified−kotlin−stdlib−jdk7−1.6.21(org.jetbrains.kotlin:kotlin−stdlib−jdk7:1.6.21)Duplicateclasskotlin.internal.jdk7.JDK7PlatformImplementations
ReflectSdkVersion found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk7-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21)
Duplicate class kotlin.internal.jdk8.JDK8PlatformImplementations found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21)
Duplicate class kotlin.internal.jdk8.JDK8PlatformImplementationsReflectSdkVersion found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21) 
Duplicate class kotlin.io.path.ExperimentalPathApi found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk7-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21) 
Duplicate class kotlin.io.path.PathRelativizer found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk7-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21) 
Duplicate class kotlin.io.path.PathsKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk7-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21) 
Duplicate class kotlin.io.path.PathsKt__PathReadWriteKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk7-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21) 
Duplicate class kotlin.io.path.PathsKt__PathUtilsKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk7-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21) 
Duplicate class kotlin.jdk7.AutoCloseableKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk7-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21) 
Duplicate class kotlin.jvm.jdk8.JvmRepeatableKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21) 
Duplicate class kotlin.random.jdk8.PlatformThreadLocalRandom found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21) 
Duplicate class kotlin.streams.jdk8.StreamsKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21) 
Duplicate class kotlin.streams.jdk8.StreamsKt
asSequence
inlined$Sequence$1foundinmodulesjetified−kotlin−stdlib−1.8.0(org.jetbrains.kotlin:kotlin−stdlib:1.8.0)andjetified−kotlin−stdlib−jdk8−1.6.21(org.jetbrains.kotlin:kotlin−stdlib−jdk8:1.6.21)Duplicateclasskotlin.streams.jdk8.StreamsKt$asSequence
inlinedSequence
2 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21)
Duplicate class kotlin.streams.jdk8.StreamsKtasSequence
inlined
Sequence3foundinmodulesjetified−kotlin−stdlib−1.8.0(org.jetbrains.kotlin:kotlin−stdlib:1.8.0)andjetified−kotlin−stdlib−jdk8−1.6.21(org.jetbrains.kotlin:kotlin−stdlib−jdk8:1.6.21)Duplicateclasskotlin.streams.jdk8.StreamsKt
asSequence$$inlined$Sequence$4 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21)
Duplicate class kotlin.text.jdk8.RegexExtensionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21)
Duplicate class kotlin.time.jdk8.DurationConversionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21)

**Comment by Janzjoy** [comment]
mmkv版本改成这个`com.tencent:mmkv-static:1.2.12`

**Comment by hidemobile** [comment]
implementation "com.tencent:mmkv-static:1.2.12" 可以编译了

**Comment by jrfeng** [comment]
排除 `mmkv` 的依赖传递：

```gradle
implementation ('com.github.jrfeng.snow:player:1.2.13') {
    exclude group: 'com.tencent', module: 'mmkv-static'
}
```
