### ISSUE TITLE
音乐进度监听器除了DataBinding，支持传统的回调监听方式吗？

### ISSUE THREAD

**Issue by LankyBin** [jrfeng/snow#59]
在demo代码里只看到在布局里通过databinding使用PlayerViewModel来刷新数据
有没有类似PlayerClient.OnPlaybackStateChangeListener()的回调函数支持传统的更新方式？

**Comment by jrfeng** [comment]
https://github.com/jrfeng/snow/wiki/%5BZH%5D-2.%E8%BF%9B%E9%98%B6#%E7%9B%91%E5%90%AC%E6%92%AD%E6%94%BE%E5%99%A8%E7%8A%B6%E6%80%81

**Comment by jrfeng** [comment]
可以使用这个类：[`LiveProgress`](https://github.com/jrfeng/snow/blob/master/player/src/main/java/snow/player/util/LiveProgress.java)

**Comment by LankyBin** [comment]
谢谢回复，
已通过：
`import snow.player.util.ProgressClock;`
实现
