### ISSUE TITLE
点击系统音乐通知栏不能跳转到播放界面

### ISSUE THREAD

**Issue by LankyBin** [jrfeng/snow#60]
demoAPP存在此问题，仿照教程自己写的app也存在同样的问题，是否缺少了调用某个API用以绑定服务前台activity的步骤？

**Comment by jrfeng** [comment]
需要自定义，继承 [`PlayerService.MediaNotificationView`](https://jrfeng.github.io/snow-doc/snow/player/PlayerService.MediaNotificationView.html) 并覆盖 `onBuildNotification` 方法方法，该方法接收一个 `NotificationCompat.Builder` 对象，使用它就能对通知进行自定义。具体请参考 [`AppPlayerService#onBuildNotification()`](https://github.com/jrfeng/snow/blob/master/app/src/main/java/snow/music/service/AppPlayerService.java#L150) 的源码。

相关文档:

- [自定义 Notification](https://github.com/jrfeng/snow/wiki/%5BZH%5D-4.%E8%87%AA%E5%AE%9A%E4%B9%89-Notification)
- [设置通知的点按操作](https://developer.android.google.cn/develop/ui/views/notifications/build-notification?hl=zh-cn#tap)

**Comment by LankyBin** [comment]
这个只能解决notification的跳转，那如果是Launcher上的音乐小组件点击跳转呢？

**Comment by LankyBin** [comment]
好的好的，谢谢解答。
