### ISSUE TITLE
How PlayerClient get all other class?

### ISSUE THREAD

**Issue by Naguchennai** [jrfeng/snow#61]
playerClient = PlayerClient.newInstance(this, MyPlayerService.class);

how can i get this playerClient  all other page? i must creat new PlayerClient.newInstance every page? or can i use static playerclient 
laike "public static PlayerClient playerClient;" pls help i need understand for clear work

**Comment by jrfeng** [comment]
Create new `PlayerClient.newInstance` every page.

**Comment by Naguchennai** [comment]
oh ok thank you ...
