### ISSUE TITLE
MyFactory Conected with where?

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#7]
Bro I just Import your library to my app. 

     `implementation project(path: ':player')
    implementation project(path: ':exo')`

    `include ':exo'
     include ':player'`

I also added MyFactory.class and codes.  but MyFactory conected with nothing .. So again m3u8 Not work and also redirect urls not work..

But working fine  if i import github library separately ..  in you library MyFactory.class conected with your doc pages ..not code...

If i add to my app where I should conect MyFactory.class ?

**Comment by jrfeng** [comment]
Your custom `PlayerService.ComponentFactory` need use `<meta-data>` register at `AndroidManifest.xml`.

Example:

```xml
<service android:name="snow.player.PlayerService">
    ...
    <meta-data android:name="component-factory" android:value="@string/factory-name"/>
</service>
```

The value of `android:name` is `"component-factory"`, and the value of `android:value` is a string resource, that is the full name of you custom `PlayerService.ComponentFactory`, example: `snow.player.debug.MyFactory`

**Comment by webwayscript** [comment]
Yes Bro Thank you its working fine..
