### ISSUE TITLE
We need pass Mediaitem inside MyFactory

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#8]
We need use More conditions inside MyFactory.class

For example in my App we using three kind of urls
1.Normal
2. Custom User agent      //Some urls need pass special user agent 
2. Need Authentication    // Some Urls need Login

Right now we  access  only "url" inside MyFactory . We meed access all MediaItem inside MyFactory 

ex We need like this 

     `  public MusicPlayer createMusicPlayer(@NonNull Context context, @NonNull **MusicItem musicItem**) {
            if(musicItem.type.Contain("useragent1"){
                  useragent = "bbbb";
          ]else{
             useragent = "ccc";
         }
         if(musicItem.type.Contain("needlogin"){
              we can use okhttp authentication 

May be we can use "extra" for or we need **"Type"  and "Categories "** for inside model.. I Bellevue you understand

**Comment by jrfeng** [comment]
@webwayscript This method has been refactored:

 ```java
public MusicPlayer createMusicPlayer(
    @NonNull Context context, 
    @NonNull MusicItem musicItem, 
    @NonNull Uri uri
)
```

**Comment by webwayscript** [comment]
Thank you Bro its working all fine now .. Thank you
