### ISSUE TITLE
Some https Urls not work

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#9]
https://stream.zenolive.com/7w4w5kt7hqzuv.aac
This Url From Very popular and open free Audio Stream Creator site called https://zeno.fm/ working fine without https.
Its only hapening old apis like api 18
     
     `Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

We already using enableTls12OnPreLollipop inside MyFactory All other https working fine

     ` OkHttpClient.Builder builder = new OkHttpClient.Builder()
                    .followRedirects(true)
                    .followSslRedirects(true)
                    .retryOnConnectionFailure(true)
                    .connectTimeout(10, TimeUnit.SECONDS)
                    .writeTimeout(20, TimeUnit.SECONDS)
                    .readTimeout(20, TimeUnit.SECONDS);
            OkHttpUtil.enableTls12OnPreLollipop(builder);
           httpDataSourceFactory = new OkHttpDataSourceFactory(builder.build(), "xxx-xxx");`

**Comment by jrfeng** [comment]
@webwayscript added a new method that works fine (but unsafe):

```java
OkHttpUtil.enableTls12OnPreLollipop(
    OkHttpClient.Builder builder,
    boolean trustAllCertificate
)
```

Trust all certificate:

```java
// unsafe
OkHttpUtil.enableTls12OnPreLollipop(builder, true);
```

**Comment by webwayscript** [comment]
Thank you Bro everything working fine now
